# Change these first
owner: hoytnix # Your GitHub organization or username, where this repository lives
repo: 8008-uptime # The name of this repository

sites:
  - name: 8008.is
    url: https://8008.is

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /8008-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 8008.is Uptime
  introTitle: "**8008.is** ICELAND HOSTING FOR NINJAS & PIRATES"
  introMessage: This is a simple status page.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
